import { useState, useEffect, useCallback } from 'react';
import { ArrowLeft, Plus } from 'lucide-react';
import { useToast } from '../../contexts/ToastContext';
import { DropdownSelect } from '../ui';
import { productService, supplierService, referenceDataService } from '../../services';
import { VariantInput } from '../../services/ProductService';
import { VariantTableRow, VariantRowData } from './VariantTableRow';

const UNITS = [
  { value: 'piece', label: 'Piece' },
  { value: 'yard', label: 'Yard' },
  { value: 'meter', label: 'Meter' },
  { value: 'pack', label: 'Pack' },
];

interface ProductInfo {
  sku: string;
  name: string;
  brand: string;
  description: string;
  category: string;
  gender: string;
  material: string;
  unit: string;
  image_url: string;
}

export interface DefaultPricing {
  supplier_id: string;
}

interface AddProductPageProps {
  mode: 'add' | 'edit';
  productId?: string;
  onSave: () => void;
  onCancel: () => void;
  initialBrand?: string;
  initialPricing?: DefaultPricing;
  onSaveAndNext?: (brand: string, pricing: DefaultPricing) => void;
}

function emptyRow(parentSku: string, index: number): VariantRowData {
  return {
    size: '',
    color: '',
    sku: parentSku ? `${parentSku}-${index + 1}` : '',
    skuAutoGenerated: true,
    qty: 0,
    cost_price: 0,
    markup_percentage: 0,
    selling_price: 0,
    reorder_level: 0,
  };
}

export function AddProductPage({
  mode, productId, onSave, onCancel, initialBrand = '', initialPricing, onSaveAndNext,
}: AddProductPageProps) {
  const { showToast } = useToast();
  const [suppliers, setSuppliers] = useState<{ id: string; name: string }[]>([]);
  const [saving, setSaving] = useState(false);
  const [refBrands, setRefBrands] = useState<string[]>([]);
  const [refCategories, setRefCategories] = useState<string[]>([]);
  const [refMaterials, setRefMaterials] = useState<string[]>([]);
  const [refNames, setRefNames] = useState<string[]>([]);

  const [info, setInfo] = useState<ProductInfo>({
    sku: '', name: '', brand: initialBrand, description: '',
    category: '', gender: '', material: '', unit: 'piece', image_url: '',
  });

  const [pricing, setPricing] = useState<DefaultPricing>(
    initialPricing ?? { supplier_id: '' }
  );

  const [rows, setRows] = useState<VariantRowData[]>([emptyRow('', 0)]);
  const [loadingProduct, setLoadingProduct] = useState(mode === 'edit');
  const [skuManuallyEdited, setSkuManuallyEdited] = useState(false);

  useEffect(() => {
    supplierService.getActiveSuppliers().then(s => setSuppliers(s)).catch(() => {});
    referenceDataService.getActiveNames('brand').then(setRefBrands).catch(() => {});
    referenceDataService.getActiveNames('category').then(setRefCategories).catch(() => {});
    referenceDataService.getActiveNames('material').then(setRefMaterials).catch(() => {});
    referenceDataService.getActiveNames('product_name').then(setRefNames).catch(() => {});
  }, []);

  // Generate SKU on mount and whenever brand/category changes (add mode only, not manually edited)
  useEffect(() => {
    if (mode !== 'add' || skuManuallyEdited) return;
    productService.generateNextSku(info.brand, info.category).then(sku => {
      setInfo(prev => ({ ...prev, sku }));
      setRows(prev => prev.map(r => r.skuAutoGenerated
        ? { ...r, sku: [sku, r.size, r.color].filter(Boolean).map(s => s.replace(/\s+/g, '').toUpperCase()).join('-') }
        : r
      ));
    }).catch(() => {});
  }, [mode, info.brand, info.category, skuManuallyEdited]);

  useEffect(() => {
    if (mode !== 'edit' || !productId) return;
    productService.getProductWithVariants(productId).then(p => {
      if (!p) return;
      setInfo({
        sku: p.sku,
        name: p.name,
        brand: (p as any).brand || '',
        description: p.description || '',
        category: p.category || '',
        gender: (p as any).gender || '',
        material: (p as any).material || '',
        unit: p.unit,
        image_url: p.image_url || '',
      });
      if (p.variants.length > 0) {
        const firstBatch = (p.variants[0] as any).batches?.[0];
        if (firstBatch) setPricing({ supplier_id: firstBatch.supplier_id });
        setRows(p.variants.map(v => {
          const batch = (v as any).batches?.[0];
          return {
            id: v.id,
            size: v.size || '',
            color: v.color || '',
            sku: v.sku,
            skuAutoGenerated: false,
            qty: 0,
            cost_price: batch?.cost_price ?? 0,
            markup_percentage: batch?.markup_percentage ?? 0,
            selling_price: batch?.selling_price ?? 0,
            reorder_level: v.reorder_level,
            existing_stock: (v as any).total_stock,
          };
        }));
      }
      setLoadingProduct(false);
    }).catch(() => setLoadingProduct(false));
  }, [mode, productId]);

  const addRow = useCallback(() => {
    setRows(prev => [...prev, emptyRow(info.sku, prev.length)]);
  }, [info.sku]);

  function deleteRow(index: number) {
    setRows(prev => prev.filter((_, i) => i !== index));
  }

  function updateRow(index: number, row: VariantRowData) {
    setRows(prev => prev.map((r, i) => i === index ? row : r));
  }

  async function handleAddStock(index: number, intake: { supplier_id: string; qty: number; cost_price: number; markup_percentage: number }) {
    if (!productId) return;
    const row = rows[index];
    if (!row.id) return;
    const client = (productService as any).productRepo.adapter.getClient();
    const selling = parseFloat((intake.cost_price * (1 + intake.markup_percentage / 100)).toFixed(2));
    const { error } = await client.from('product_batches').insert({
      variant_id: row.id,
      supplier_id: intake.supplier_id,
      batch_number: `B-${Date.now()}-${Math.random().toString(36).slice(2, 5).toUpperCase()}`,
      cost_price: intake.cost_price,
      markup_percentage: intake.markup_percentage,
      selling_price: selling,
      initial_quantity: intake.qty,
      current_quantity: intake.qty,
      received_date: new Date().toISOString().split('T')[0],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    });
    if (error) throw new Error(error.message);
    setRows(prev => prev.map((r, i) => i === index
      ? { ...r, existing_stock: (r.existing_stock ?? 0) + intake.qty }
      : r
    ));
    showToast(`Added ${intake.qty} units to stock`, 'success');
  }

  function buildVariantInputs(): VariantInput[] {
    return rows
      .filter(r => !r.id)
      .map(r => ({
        size: r.size.trim() || null,
        color: r.color.trim() || null,
        sku: r.sku.trim() || `${info.sku}-${Date.now()}`,
        barcode: r.sku.trim() || null,
        reorder_level: r.reorder_level,
        qty: r.qty,
        selling_price: r.selling_price,
        cost_price: r.cost_price,
        markup_percentage: r.markup_percentage,
        supplier_id: pricing.supplier_id,
      }));
  }

  function validate(): string | null {
    if (!info.name.trim()) return 'Product name is required.';
    if (!info.sku.trim()) return 'SKU is required.';
    const newRows = rows.filter(r => !r.id);
    if (mode === 'add' && newRows.length === 0) return 'At least one variant is required.';
    if (newRows.some(r => r.qty > 0 && !pricing.supplier_id)) return 'Select a supplier for stock intake.';
    return null;
  }

  async function doSave(andNext: boolean) {
    const err = validate();
    if (err) { showToast(err, 'error'); return; }
    setSaving(true);
    try {
      if (mode === 'add') {
        const allRows: VariantInput[] = rows.map(r => ({
          size: r.size.trim() || null,
          color: r.color.trim() || null,
          sku: r.sku.trim() || `${info.sku}-${Date.now()}`,
          barcode: r.sku.trim() || null,
          reorder_level: r.reorder_level,
          qty: r.qty,
          selling_price: r.selling_price,
          cost_price: r.cost_price,
          markup_percentage: r.markup_percentage,
          supplier_id: pricing.supplier_id,
        }));
        await productService.createProductWithVariants(info, allRows);
        showToast(`${info.name} saved — ${rows.length} variant${rows.length > 1 ? 's' : ''} added`, 'success');
      } else if (productId) {
        const newVariants = buildVariantInputs();
        await productService.updateProductWithVariants(productId, info, newVariants);
        showToast('Product updated', 'success');
      }

      if (andNext && onSaveAndNext) {
        setSkuManuallyEdited(false);
        onSaveAndNext(info.brand, pricing);
      } else {
        onSave();
      }
    } catch (e: any) {
      showToast(e.message || 'Failed to save', 'error');
    } finally {
      setSaving(false);
    }
  }

  if (loadingProduct) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: 300 }}>
        <div className="animate-spin" style={{ width: 32, height: 32, borderRadius: '50%', border: '2px solid var(--line)', borderTopColor: 'var(--accent)' }} />
      </div>
    );
  }

  const labelStyle: React.CSSProperties = { display: 'block', fontSize: 11.5, fontWeight: 600, color: 'var(--muted)', marginBottom: 5, textTransform: 'uppercase', letterSpacing: '.05em' };
  const inputStyle: React.CSSProperties = { width: '100%', height: 36, padding: '0 10px', border: '1px solid var(--line)', borderRadius: 8, fontSize: 13, color: 'var(--ink)', background: 'var(--panel)', outline: 'none', boxSizing: 'border-box' };
  const sectionStyle: React.CSSProperties = { background: 'var(--panel)', border: '1px solid var(--line)', borderRadius: 12, padding: '18px 20px', display: 'flex', flexDirection: 'column', gap: 14 };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
        <button type="button" onClick={onCancel} className="btn btn-sm" style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <ArrowLeft size={13} /> Products
        </button>
        <h2 style={{ margin: 0, fontSize: 20, fontWeight: 600, color: 'var(--ink)', letterSpacing: '-0.02em' }}>
          {mode === 'add' ? 'Add Product' : 'Edit Product'}
        </h2>
      </div>

      {/* Product Info */}
      <div style={sectionStyle}>
        <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '.06em' }}>Product Info</div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
          <div>
            <label style={labelStyle}>Brand</label>
            <DropdownSelect
              value={info.brand}
              onChange={v => setInfo(p => ({ ...p, brand: v }))}
              options={refBrands.map(b => ({ value: b, label: b }))}
              placeholder="Select brand…"
            />
          </div>
          <div>
            <label style={labelStyle}>SKU <span style={{ color: 'var(--danger)' }}>*</span></label>
            <input
              style={{ ...inputStyle, fontFamily: "'JetBrains Mono', monospace", fontSize: 12 }}
              value={info.sku}
              onChange={e => {
                const newSku = e.target.value;
                setSkuManuallyEdited(true);
                setInfo(p => ({ ...p, sku: newSku }));
                setRows(prev => prev.map(r => r.skuAutoGenerated
                  ? { ...r, sku: [newSku, r.size, r.color].filter(Boolean).map(s => s.replace(/\s+/g, '').toUpperCase()).join('-') }
                  : r
                ));
              }}
              disabled={mode === 'edit'}
            />
          </div>
          <div style={{ gridColumn: '1 / -1' }}>
            <label style={labelStyle}>Product Name <span style={{ color: 'var(--danger)' }}>*</span></label>
            <DropdownSelect
              value={info.name}
              onChange={v => setInfo(p => ({ ...p, name: v }))}
              options={refNames.map(n => ({ value: n, label: n }))}
              placeholder="Select product name…"
            />
          </div>
          <div>
            <label style={labelStyle}>Category</label>
            <DropdownSelect
              value={info.category}
              onChange={v => setInfo(p => ({ ...p, category: v }))}
              options={refCategories.map(c => ({ value: c, label: c }))}
              placeholder="Select category…"
            />
          </div>
          <div>
            <label style={labelStyle}>Gender</label>
            <DropdownSelect
              value={info.gender}
              onChange={v => setInfo(p => ({ ...p, gender: v }))}
              options={[
                { value: 'men', label: 'Men' },
                { value: 'women', label: 'Women' },
                { value: 'kids', label: 'Kids' },
                { value: 'unisex', label: 'Unisex' },
              ]}
              placeholder="Select gender…"
            />
          </div>
          <div>
            <label style={labelStyle}>Material</label>
            <DropdownSelect
              value={info.material}
              onChange={v => setInfo(p => ({ ...p, material: v }))}
              options={refMaterials.map(m => ({ value: m, label: m }))}
              placeholder="Select material…"
            />
          </div>
          <div>
            <label style={labelStyle}>Unit</label>
            <DropdownSelect
              value={info.unit}
              onChange={v => setInfo(p => ({ ...p, unit: v }))}
              options={UNITS.map(u => ({ value: u.value, label: u.label }))}
              placeholder="Select unit…"
            />
          </div>
          <div style={{ gridColumn: '1 / -1' }}>
            <label style={labelStyle}>Image URL</label>
            <input style={inputStyle} type="url" value={info.image_url} onChange={e => setInfo(p => ({ ...p, image_url: e.target.value }))} placeholder="https://…" />
          </div>
        </div>
      </div>

      {/* Supplier */}
      <div style={sectionStyle}>
        <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '.06em' }}>Supplier</div>
        <div style={{ maxWidth: 320 }}>
          <label style={labelStyle}>Default Supplier</label>
          <DropdownSelect
            value={pricing.supplier_id}
            onChange={v => setPricing({ supplier_id: v })}
            options={suppliers.map(s => ({ value: s.id, label: s.name }))}
            placeholder="Select supplier…"
          />
        </div>
        <div style={{ fontSize: 11.5, color: 'var(--muted)' }}>
          Set cost, markup, and selling price per variant below.
        </div>
      </div>

      {/* Variants */}
      <div style={{ ...sectionStyle, padding: 0, overflow: 'hidden' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 20px', borderBottom: '1px solid var(--line-2)' }}>
          <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '.06em' }}>
            Variants <span style={{ fontSize: 11, fontWeight: 500, color: 'var(--faint)', textTransform: 'none', letterSpacing: 0 }}>({rows.length})</span>
          </div>
          <button type="button" onClick={addRow} className="btn btn-sm" style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
            <Plus size={12} /> Add Row
          </button>
        </div>

        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: 860 }}>
            <thead>
              <tr style={{ background: 'var(--panel-2)', borderBottom: '1px solid var(--line-2)' }}>
                {['Size', 'Colour', 'SKU', 'Min Stock', mode === 'edit' ? 'Stock' : 'Qty', 'Cost (LKR)', 'Markup %', 'Selling (LKR)', ''].map(h => (
                  <th key={h} style={{ padding: '8px 4px', textAlign: h === '' ? 'left' : ['Cost (LKR)', 'Markup %', 'Selling (LKR)', 'Min Stock', mode === 'edit' ? 'Stock' : 'Qty'].includes(h) ? 'right' : 'left', fontSize: 10.5, fontWeight: 600, letterSpacing: '.06em', textTransform: 'uppercase', color: 'var(--muted)', whiteSpace: 'nowrap' }}>
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows.map((row, i) => (
                <VariantTableRow
                  key={row.id ?? i}
                  row={row}
                  index={i}
                  defaultSupplierId={pricing.supplier_id}
                  suppliers={suppliers}
                  mode={mode}
                  parentSku={info.sku}
                  isOnly={rows.length === 1}
                  onChange={updateRow}
                  onDelete={deleteRow}
                  onAddStock={mode === 'edit' ? handleAddStock : undefined}
                  onTabFromLastCell={i === rows.length - 1 ? addRow : undefined}
                />
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Actions */}
      <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 10, paddingBottom: 32 }}>
        <button type="button" onClick={onCancel} className="btn">Cancel</button>
        {mode === 'add' && onSaveAndNext && (
          <button type="button" onClick={() => doSave(true)} disabled={saving} className="btn">
            {saving ? 'Saving…' : 'Save & Add Next'}
          </button>
        )}
        <button type="button" onClick={() => doSave(false)} disabled={saving} className="btn btn-primary">
          {saving ? 'Saving…' : mode === 'add' ? 'Save Product' : 'Update Product'}
        </button>
      </div>
    </div>
  );
}
