import { useState } from 'react';
import { X, Plus, RotateCcw } from 'lucide-react';

export interface VariantRowData {
  id?: string;
  size: string;
  color: string;
  sku: string;
  skuAutoGenerated: boolean;
  barcode: string;
  qty: number;
  priceOverride: number | null;
  reorder_level: number;
  existing_stock?: number;
}

interface StockIntakeData {
  supplier_id: string;
  qty: number;
  cost_price: number;
  markup_percentage: number;
}

interface VariantTableRowProps {
  row: VariantRowData;
  index: number;
  defaultSellingPrice: number;
  defaultCostPrice: number;
  defaultMarkup: number;
  defaultSupplierId: string;
  suppliers: { id: string; name: string }[];
  mode: 'add' | 'edit';
  parentSku: string;
  isOnly: boolean;
  onChange: (index: number, row: VariantRowData) => void;
  onDelete: (index: number) => void;
  onAddStock?: (index: number, intake: StockIntakeData) => Promise<void>;
  onTabFromLastCell?: () => void;
}

function autoSku(parentSku: string, size: string, color: string): string {
  const parts = [parentSku, size, color].filter(Boolean).map(s => s.replace(/\s+/g, '').toUpperCase());
  return parts.join('-');
}

export function VariantTableRow({
  row, index, defaultSellingPrice, defaultCostPrice, defaultMarkup, defaultSupplierId,
  suppliers, mode, parentSku, isOnly, onChange, onDelete, onAddStock, onTabFromLastCell,
}: VariantTableRowProps) {
  const [showStockIntake, setShowStockIntake] = useState(false);
  const [intakeSupplierId, setIntakeSupplierId] = useState(defaultSupplierId);
  const [intakeQty, setIntakeQty] = useState(0);
  const [intakeCost, setIntakeCost] = useState(defaultCostPrice);
  const [intakeMarkup, setIntakeMarkup] = useState(defaultMarkup);
  const [intakeSaving, setIntakeSaving] = useState(false);

  const effectivePrice = row.priceOverride ?? defaultSellingPrice;
  const isPriceOverridden = row.priceOverride !== null;

  function update(patch: Partial<VariantRowData>) {
    const updated = { ...row, ...patch };
    if (('size' in patch || 'color' in patch) && updated.skuAutoGenerated) {
      updated.sku = autoSku(parentSku, updated.size, updated.color);
    }
    onChange(index, updated);
  }

  async function submitStockIntake() {
    if (!onAddStock || intakeQty <= 0) return;
    setIntakeSaving(true);
    try {
      await onAddStock(index, {
        supplier_id: intakeSupplierId,
        qty: intakeQty,
        cost_price: intakeCost,
        markup_percentage: intakeMarkup,
      });
      setShowStockIntake(false);
      setIntakeQty(0);
    } finally {
      setIntakeSaving(false);
    }
  }

  const cellStyle: React.CSSProperties = { padding: '6px 4px', verticalAlign: 'middle' };
  const inputStyle: React.CSSProperties = {
    width: '100%',
    height: 32,
    padding: '0 8px',
    border: '1px solid var(--line)',
    borderRadius: 6,
    background: 'var(--panel)',
    fontSize: 12.5,
    color: 'var(--ink)',
    outline: 'none',
    boxSizing: 'border-box',
  };

  return (
    <>
      <tr style={{ borderBottom: '1px solid var(--line-2)' }}>
        {/* Size */}
        <td style={cellStyle}>
          <input
            style={inputStyle}
            value={row.size}
            onChange={e => update({ size: e.target.value })}
            placeholder="S / 30 / XL"
          />
        </td>

        {/* Colour */}
        <td style={cellStyle}>
          <input
            style={inputStyle}
            value={row.color}
            onChange={e => update({ color: e.target.value })}
            placeholder="Black"
          />
        </td>

        {/* SKU */}
        <td style={cellStyle}>
          <input
            style={{ ...inputStyle, fontFamily: "'JetBrains Mono', monospace", fontSize: 11.5 }}
            value={row.sku}
            onChange={e => update({ sku: e.target.value, skuAutoGenerated: false })}
            placeholder="Auto"
          />
        </td>

        {/* Barcode */}
        <td style={cellStyle}>
          <input
            style={{ ...inputStyle, fontFamily: "'JetBrains Mono', monospace", fontSize: 11.5 }}
            value={row.barcode}
            onChange={e => update({ barcode: e.target.value })}
            placeholder="Scan or type"
          />
        </td>

        {/* Qty — editable in add mode, read-only in edit mode for existing variants */}
        <td style={{ ...cellStyle, width: 88 }}>
          {mode === 'edit' && row.id ? (
            <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
              <span className="num" style={{ fontSize: 12.5, color: (row.existing_stock ?? 0) === 0 ? 'var(--danger)' : 'var(--pos)', fontWeight: 600 }}>
                {row.existing_stock ?? 0}
              </span>
              <button
                type="button"
                onClick={() => setShowStockIntake(s => !s)}
                title="Add stock"
                style={{ width: 22, height: 22, borderRadius: 4, border: '1px solid var(--line)', background: showStockIntake ? 'var(--accent-soft)' : 'var(--panel)', color: showStockIntake ? 'var(--accent)' : 'var(--muted)', display: 'grid', placeItems: 'center', cursor: 'default', flexShrink: 0 }}
              >
                <Plus size={11} />
              </button>
            </div>
          ) : (
            <input
              style={{ ...inputStyle, textAlign: 'right' }}
              type="number"
              min={0}
              value={row.qty || ''}
              onChange={e => update({ qty: parseInt(e.target.value) || 0 })}
              placeholder="0"
            />
          )}
        </td>

        {/* Price */}
        <td style={{ ...cellStyle, width: 110 }}>
          <div style={{ position: 'relative' }}>
            <input
              style={{
                ...inputStyle,
                textAlign: 'right',
                color: isPriceOverridden ? 'var(--ink)' : 'var(--muted)',
                paddingRight: isPriceOverridden ? 24 : 8,
              }}
              type="number"
              min={0}
              value={isPriceOverridden ? row.priceOverride! : (effectivePrice || '')}
              onChange={e => update({ priceOverride: parseFloat(e.target.value) || null })}
              placeholder={defaultSellingPrice ? String(defaultSellingPrice) : '0'}
              onFocus={() => { if (!isPriceOverridden && defaultSellingPrice) update({ priceOverride: defaultSellingPrice }); }}
            />
            {isPriceOverridden && (
              <button
                type="button"
                onClick={() => update({ priceOverride: null })}
                title="Reset to default price"
                style={{ position: 'absolute', right: 4, top: '50%', transform: 'translateY(-50%)', border: 0, background: 'transparent', color: 'var(--muted)', cursor: 'default', padding: 0, lineHeight: 0 }}
              >
                <RotateCcw size={10} />
              </button>
            )}
          </div>
        </td>

        {/* Delete */}
        <td style={{ ...cellStyle, width: 32, paddingLeft: 4 }}>
          {!isOnly && (
            <button
              type="button"
              onClick={() => onDelete(index)}
              style={{ width: 24, height: 24, borderRadius: 4, border: 0, background: 'transparent', color: 'var(--faint)', cursor: 'default', display: 'grid', placeItems: 'center' }}
              onMouseEnter={e => { e.currentTarget.style.color = 'var(--danger)'; e.currentTarget.style.background = 'var(--danger-soft)'; }}
              onMouseLeave={e => { e.currentTarget.style.color = 'var(--faint)'; e.currentTarget.style.background = 'transparent'; }}
            >
              <X size={12} />
            </button>
          )}
        </td>
      </tr>

      {/* Inline stock intake form — edit mode only */}
      {showStockIntake && (
        <tr>
          <td colSpan={7} style={{ padding: '0 4px 10px', background: 'var(--panel-2)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 12px', border: '1px solid var(--line)', borderRadius: 8, flexWrap: 'wrap' }}>
              <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--ink)', flexShrink: 0 }}>
                {[row.size, row.color].filter(Boolean).join(' · ') || 'Default'}
              </span>
              <select
                value={intakeSupplierId}
                onChange={e => setIntakeSupplierId(e.target.value)}
                style={{ height: 30, padding: '0 8px', border: '1px solid var(--line)', borderRadius: 6, fontSize: 12, color: 'var(--ink)', background: 'var(--panel)' }}
              >
                <option value="">Supplier</option>
                {suppliers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
              </select>
              <input type="number" min={1} value={intakeQty || ''} onChange={e => setIntakeQty(parseInt(e.target.value) || 0)}
                placeholder="Qty" style={{ width: 64, height: 30, padding: '0 8px', border: '1px solid var(--line)', borderRadius: 6, fontSize: 12, textAlign: 'right', background: 'var(--panel)' }} />
              <input type="number" min={0} step="any" value={intakeCost || ''} onChange={e => setIntakeCost(parseFloat(e.target.value) || 0)}
                placeholder="Cost" style={{ width: 80, height: 30, padding: '0 8px', border: '1px solid var(--line)', borderRadius: 6, fontSize: 12, textAlign: 'right', background: 'var(--panel)' }} />
              <input type="number" min={0} step="any" value={intakeMarkup || ''} onChange={e => setIntakeMarkup(parseFloat(e.target.value) || 0)}
                placeholder="Markup %" style={{ width: 80, height: 30, padding: '0 8px', border: '1px solid var(--line)', borderRadius: 6, fontSize: 12, textAlign: 'right', background: 'var(--panel)' }} />
              <button
                type="button"
                onClick={submitStockIntake}
                disabled={intakeSaving || intakeQty <= 0 || !intakeSupplierId}
                className="btn btn-sm btn-primary"
                style={{ flexShrink: 0 }}
              >
                {intakeSaving ? 'Saving…' : 'Add Batch'}
              </button>
              <button type="button" onClick={() => setShowStockIntake(false)}
                style={{ width: 26, height: 26, borderRadius: 5, border: 0, background: 'transparent', color: 'var(--muted)', cursor: 'default', display: 'grid', placeItems: 'center' }}>
                <X size={13} />
              </button>
            </div>
          </td>
        </tr>
      )}
    </>
  );
}
