import { X } from 'lucide-react';

export interface VariantRowData {
  id?: string;
  size: string;
  color: string;
  sku: string;
  skuAutoGenerated: boolean;
  qty: number;
  cost_price: number;
  markup_percentage: number;
  selling_price: number;
  reorder_level: number;
  existing_stock?: number;
}

interface VariantTableRowProps {
  row: VariantRowData;
  index: number;
  defaultSupplierId: string;
  suppliers: { id: string; name: string }[];
  mode: 'add' | 'edit';
  parentSku: string;
  isOnly: boolean;
  showPricing?: boolean;
  onChange: (index: number, row: VariantRowData) => void;
  onDelete: (index: number) => void;
  onTabFromLastCell?: () => void;
}

function autoSku(parentSku: string, size: string, color: string): string {
  const parts = [parentSku, size, color].filter(Boolean).map(s => s.replace(/\s+/g, '').toUpperCase());
  return parts.join('-');
}

export function VariantTableRow({
  row, index, defaultSupplierId,
  suppliers, mode, parentSku, isOnly, showPricing = true, onChange, onDelete, onTabFromLastCell,
}: VariantTableRowProps) {

  function update(patch: Partial<VariantRowData>) {
    const updated = { ...row, ...patch };
    if (('size' in patch || 'color' in patch) && updated.skuAutoGenerated) {
      updated.sku = autoSku(parentSku, updated.size, updated.color);
    }
    onChange(index, updated);
  }

  function updateCost(cost: number) {
    const selling = parseFloat((cost * (1 + row.markup_percentage / 100)).toFixed(2));
    update({ cost_price: cost, selling_price: selling });
  }

  function updateMarkup(markup: number) {
    const selling = parseFloat((row.cost_price * (1 + markup / 100)).toFixed(2));
    update({ markup_percentage: markup, selling_price: selling });
  }

  function updateSelling(selling: number) {
    const markup = row.cost_price > 0
      ? parseFloat(((selling - row.cost_price) / row.cost_price * 100).toFixed(2))
      : 0;
    update({ selling_price: selling, markup_percentage: markup });
  }

  const cellStyle: React.CSSProperties = { padding: '6px 4px', verticalAlign: 'middle' };
  const inputStyle: React.CSSProperties = {
    width: '100%', height: 32, padding: '0 8px',
    border: '1px solid var(--line)', borderRadius: 6,
    background: 'var(--panel)', fontSize: 12.5, color: 'var(--ink)',
    outline: 'none', boxSizing: 'border-box',
  };

  return (
    <>
      <tr style={{ borderBottom: '1px solid var(--line-2)' }}>
        {/* Size */}
        <td style={cellStyle}>
          <input style={inputStyle} value={row.size} onChange={e => update({ size: e.target.value })} placeholder="S / 30 / XL" />
        </td>

        {/* Colour */}
        <td style={cellStyle}>
          <input style={inputStyle} value={row.color} onChange={e => update({ color: e.target.value })} placeholder="Black" />
        </td>

        {/* SKU */}
        <td style={cellStyle}>
          <input
            style={{ ...inputStyle, fontFamily: "'JetBrains Mono', monospace", fontSize: 11.5 }}
            value={row.sku}
            onChange={e => update({ sku: e.target.value, skuAutoGenerated: false })}
            placeholder="Auto"
          />
        </td>

        {/* Min Stock */}
        <td style={{ ...cellStyle, width: 72 }}>
          <input
            style={{ ...inputStyle, textAlign: 'right' }} type="number" min={0}
            value={row.reorder_level || ''}
            onChange={e => update({ reorder_level: parseInt(e.target.value) || 0 })}
            placeholder="0"
          />
        </td>

        {/* Qty / Stock */}
        {showPricing && (
          <td style={{ ...cellStyle, width: 80 }}>
            {mode === 'edit' && row.id ? (
              <span className="num" style={{ fontSize: 12.5, color: (row.existing_stock ?? 0) === 0 ? 'var(--danger)' : 'var(--pos)', fontWeight: 600 }}>
                {row.existing_stock ?? 0}
              </span>
            ) : (
              <input
                style={{ ...inputStyle, textAlign: 'right' }} type="number" min={0}
                value={row.qty || ''}
                onChange={e => update({ qty: parseInt(e.target.value) || 0 })}
                placeholder="0"
              />
            )}
          </td>
        )}

        {/* Cost (LKR) */}
        {showPricing && (
          <td style={{ ...cellStyle, width: 96 }}>
            <input
              style={{ ...inputStyle, textAlign: 'right' }} type="number" min={0} step="any"
              value={row.cost_price || ''}
              onChange={e => updateCost(parseFloat(e.target.value) || 0)}
              placeholder="0"
            />
          </td>
        )}

        {/* Markup % */}
        {showPricing && (
          <td style={{ ...cellStyle, width: 80 }}>
            <input
              style={{ ...inputStyle, textAlign: 'right' }} type="number" min={0} step="any"
              value={row.markup_percentage || ''}
              onChange={e => updateMarkup(parseFloat(e.target.value) || 0)}
              placeholder="0"
            />
          </td>
        )}

        {/* Selling (LKR) */}
        {showPricing && (
          <td style={{ ...cellStyle, width: 96 }}>
            <input
              style={{ ...inputStyle, textAlign: 'right' }} type="number" min={0} step="any"
              value={row.selling_price || ''}
              onChange={e => updateSelling(parseFloat(e.target.value) || 0)}
              placeholder="0"
            />
          </td>
        )}

        {/* Delete */}
        <td style={{ ...cellStyle, width: 32, paddingLeft: 4 }}>
          {!isOnly && (
            <button
              type="button"
              onClick={() => onDelete(index)}
              style={{ width: 24, height: 24, borderRadius: 4, border: 0, background: 'transparent', color: 'var(--faint)', cursor: 'default', display: 'grid', placeItems: 'center' }}
              onMouseEnter={e => { e.currentTarget.style.color = 'var(--danger)'; e.currentTarget.style.background = 'var(--danger-soft)'; }}
              onMouseLeave={e => { e.currentTarget.style.color = 'var(--faint)'; e.currentTarget.style.background = 'transparent'; }}
            >
              <X size={12} />
            </button>
          )}
        </td>
      </tr>

    </>
  );
}
