-- Seed initial reference data — admins can add/edit/deactivate from Settings → Catalog

INSERT INTO reference_data (type, name) VALUES

-- ── Brands ────────────────────────────────────────────────────────────────
('brand', 'Adidas'),
('brand', 'Arrow'),
('brand', 'Calvin Klein'),
('brand', 'Champion'),
('brand', 'Columbia'),
('brand', 'H&M'),
('brand', 'Levi''s'),
('brand', 'Mango'),
('brand', 'Next'),
('brand', 'Nike'),
('brand', 'Puma'),
('brand', 'Reebok'),
('brand', 'Tommy Hilfiger'),
('brand', 'Under Armour'),
('brand', 'Uniqlo'),
('brand', 'Zara'),

-- ── Categories ────────────────────────────────────────────────────────────
('category', 'Accessories'),
('category', 'Bags'),
('category', 'Belts'),
('category', 'Coats'),
('category', 'Dresses'),
('category', 'Fabric'),
('category', 'Jackets'),
('category', 'Jeans'),
('category', 'Pants'),
('category', 'Shirts'),
('category', 'Shoes'),
('category', 'Shorts'),
('category', 'Skirts'),
('category', 'Socks'),
('category', 'Sportswear'),
('category', 'Sunglasses'),
('category', 'Swimwear'),
('category', 'T-Shirts'),
('category', 'Underwear'),
('category', 'Watches'),

-- ── Materials ─────────────────────────────────────────────────────────────
('material', 'Canvas'),
('material', 'Cashmere'),
('material', 'Chiffon'),
('material', 'Cotton'),
('material', 'Denim'),
('material', 'Fleece'),
('material', 'Jersey'),
('material', 'Leather'),
('material', 'Linen'),
('material', 'Nylon'),
('material', 'Polyester'),
('material', 'Rayon'),
('material', 'Satin'),
('material', 'Silk'),
('material', 'Spandex'),
('material', 'Suede'),
('material', 'Velvet'),
('material', 'Viscose'),
('material', 'Wool'),

-- ── Product Names ─────────────────────────────────────────────────────────
('product_name', 'Bomber Jacket'),
('product_name', 'Button-Down Shirt'),
('product_name', 'Cargo Pants'),
('product_name', 'Casual Dress'),
('product_name', 'Chino Pants'),
('product_name', 'Crew Neck Sweater'),
('product_name', 'Denim Jacket'),
('product_name', 'Denim Shorts'),
('product_name', 'Floral Dress'),
('product_name', 'Graphic T-Shirt'),
('product_name', 'Hoodie'),
('product_name', 'Jogger Pants'),
('product_name', 'Kurti'),
('product_name', 'Leggings'),
('product_name', 'Linen Shirt'),
('product_name', 'Maxi Dress'),
('product_name', 'Midi Skirt'),
('product_name', 'Mini Skirt'),
('product_name', 'Oxford Shirt'),
('product_name', 'Palazzo Pants'),
('product_name', 'Plain T-Shirt'),
('product_name', 'Polo Shirt'),
('product_name', 'Running Shorts'),
('product_name', 'Saree'),
('product_name', 'Sarong'),
('product_name', 'Skinny Jeans'),
('product_name', 'Slim Fit Jeans'),
('product_name', 'Slim Fit Trouser'),
('product_name', 'Sneakers'),
('product_name', 'Sports Bra'),
('product_name', 'Straight Leg Jeans'),
('product_name', 'Strappy Top'),
('product_name', 'Summer Dress'),
('product_name', 'Sweatshirt'),
('product_name', 'Track Pants'),
('product_name', 'Turtleneck'),
('product_name', 'V-Neck T-Shirt'),
('product_name', 'Wide Leg Pants'),
('product_name', 'Wind Jacket'),
('product_name', 'Zip-Up Hoodie')

ON CONFLICT (type, lower(name)) DO NOTHING;
